### ISSUE TITLE
The current pipelinewise mongodb plugin requires the ssl value to be a String

### ISSUE THREAD

**Issue by barrett-hln** [kestra-io/plugin-singer#15]
https://github.com/kestra-io/plugin-singer/blob/3d32bb08691a01e7664f518d637635a50e87ae59/src/main/java/io/kestra/plugin/singer/taps/PipelinewiseMongoDb.java#L78

When entering the `ssl` or `sslVerify` values as string values (quoted) like `"true"` they get converted by Kestra to booleans, however the current pipelinewise mongodb tap does not work properly with non-string boolean values. A [PR is pending](https://github.com/transferwise/pipelinewise-tap-mongodb/pull/81) for modifying this in the tap, but who knows how long that will take to be merged, so would be nice to have this fixed in the Kestra plugin side.

**Comment by tchiotludo** [comment]
If I clearly understand, you need to change : 
```java
            .put("ssl", this.ssl)
            .put("verify_mode", this.sslVerify)
```
to 
```java
            .put("ssl", this.ssl.toString())
            .put("verify_mode", this.sslVerify.toString())
```
If yes, you can create a PR, I will be happy to merged :)
