### ISSUE TITLE
Refactor the Singer's logic from State Store to KV store

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-singer#71]
### Feature description

State Store is challenging to use. Users currently cannot:
- see what values are persisted across flows and namespaces
- inspect those values from the UI (see the value for a given key)
- see when the key was initially created and the last time it was updated/used

Switching from the State Store to the KV Store will address those issues.

Ideally, we would want to also tackle https://github.com/kestra-io/kestra/issues/3852

**Comment by brian-mulier-p** [comment]
I will wait for the migration mechanism to be started / finished before tackling this as it can't be released without a migration helper
